### ISSUE TITLE
Broken stats graph

### ISSUE THREAD

**Issue by sjaustirni** [fnatte/pizza-tribes#6]
When amount of pizzas hits zero, the graph gets broken. The data points are no longer sorted chronologically, but they are all around the place.

![Screenshot from 2023-04-01 12-25-17](https://user-images.githubusercontent.com/22116610/229280780-5d1fe976-0c81-454d-9f90-ff431c4c5d3d.png)
![Screenshot from 2023-04-01 12-25-21](https://user-images.githubusercontent.com/22116610/229280781-1290fa12-e050-488d-986d-96110dd93343.png)

**Comment by fnatte** [comment]
Thanks for reporting! :pizza: 

Although I've encountered this issue occasionally, I haven't been able to reproduce it consistently. So at this time I'm not sure what the problem is.

Please note that, due to the ongoing closed-source development (refer to the updated readme), I might not implement the fix in this repository.

**Comment by sjaustirni** [comment]
Hey! No worries, glad to be of help.

Yeah, I could not determine myself if it was funky data from API or the funky use of the library, (or something entirely else) that causes the bug. It's rather tricky.

No worries about that either, thanks for updating the readme!
